version: "3.9"

services:
  database:
    image: postgres:14-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=database user=postgres password=postgres dbname=portfolio port=5432 sslmode=disable"
      PORT: "8080"
    depends_on:
      - database
