# https://taskfile.dev

version: '3'

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go

  test:
    cmds:
      - go test -tags=unit -v ./...

  run:
    cmds:
      - docker-compose up --build -d

  stop:
    cmds:
      - docker-compose down

  integration-test:
    cmds:
      - docker-compose up -d database
      - go test -tags=integration -v ./...
      - docker-compose down
    env:
      DATABASE_URL: "host=localhost user=postgres password=postgres dbname=portfolio port=5432 sslmode=disable"

  e2e-test:
    cmds:
      - docker-compose up -d database
      - go test -tags=e2e -v ./...
      - docker-compose down
    env:
      DATABASE_URL: "host=localhost user=postgres password=postgres dbname=portfolio port=5432 sslmode=disable"
